#! /bin/sh

echo 'press <ENTER> to install xetch (any other installation of xetch will be overwritten)...'
read -p "" x

sudo chmod +x ../xetch

python3 -m pip install -r ../requirements.txt
sudo cp ../xetch /usr/bin/xetch

sudo chmod +x /usr/bin/xetch

echo
echo 'thanks for installing xetch'
