#! /bin/sh

echo 'press <ENTER> to install xetch (any other installation of xetch will be overwritten)...'
read -p "" x

python3 -m pip install colorama
python3 -m pip install psutil
sudo cp ../xetch /usr/bin/xetch

echo
echo 'thanks for installing xetch'
